"""initial schema

Revision ID: d4d61a9f9269
Revises:
Create Date: 2026-09-14 15:28:31.185566
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d4d61a9f9269"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role in ('teacher', 'student')", name="profiles_role"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schools",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("suburb", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "school_memberships",
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["teacher_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("teacher_id", "school_id"),
    )
    op.create_table(
        "students",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("instrument_family", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level in ('beginner', 'intermediate', 'advanced')", name="students_level"
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["teacher_id"], ["profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id"),
    )
    op.create_index(
        "students_teacher_active_idx", "students", ["teacher_id", "is_active"], unique=False
    )
    op.create_table(
        "practice_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("plan_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "source", sa.String(length=8), server_default=sa.text("'engine'"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source in ('engine', 'llm')", name="sessions_source"),
        sa.CheckConstraint("duration_minutes in (10, 20, 30)", name="sessions_duration"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "sessions_student_created_idx",
        "practice_sessions",
        ["student_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "targets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("target_tempo", sa.Integer(), nullable=False),
        sa.Column("units", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("phrases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("start_tempo", sa.Integer(), nullable=True),
        sa.Column("threshold_override", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind in ('scale', 'technique', 'repertoire')", name="targets_kind"),
        sa.CheckConstraint("jsonb_array_length(units) >= 1", name="targets_units_non_empty"),
        sa.CheckConstraint("target_tempo between 20 and 300", name="targets_tempo_range"),
        sa.CheckConstraint(
            "threshold_override is null or threshold_override between 3 and 10",
            name="targets_threshold_range",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["profiles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "targets_student_active_position_idx",
        "targets",
        ["student_id", "is_active", "position"],
        unique=False,
    )
    op.create_table(
        "prescriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["practice_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "target_states",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("target_id"),
    )
    op.create_table(
        "log_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("prescription_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("tempo_used", sa.Integer(), nullable=False),
        sa.Column("best_consecutive", sa.Integer(), nullable=False),
        sa.Column("break_unit", sa.Integer(), nullable=True),
        sa.Column("felt_difficulty", sa.Integer(), nullable=False),
        sa.Column("free_text", sa.String(length=500), nullable=True),
        sa.Column("state_after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("best_consecutive between 0 and 50", name="log_entries_best"),
        sa.CheckConstraint("felt_difficulty between 1 and 5", name="log_entries_difficulty"),
        sa.CheckConstraint("tempo_used between 20 and 300", name="log_entries_tempo"),
        sa.ForeignKeyConstraint(["prescription_id"], ["prescriptions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prescription_id"),
    )
    op.create_index(
        "log_entries_student_created_idx", "log_entries", ["student_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("log_entries_student_created_idx", table_name="log_entries")
    op.drop_table("log_entries")
    op.drop_table("target_states")
    op.drop_table("prescriptions")
    op.drop_index("targets_student_active_position_idx", table_name="targets")
    op.drop_table("targets")
    op.drop_index("sessions_student_created_idx", table_name="practice_sessions")
    op.drop_table("practice_sessions")
    op.drop_index("students_teacher_active_idx", table_name="students")
    op.drop_table("students")
    op.drop_table("school_memberships")
    op.drop_table("schools")
    op.drop_table("profiles")
    # ### end Alembic commands ###
